name: Test Python

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
      
      - name: Python set up
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
      
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: List files for debugging
        run: ls -R

      - name: Install dependencies
        run: pip install -r requirements.txt
  
      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)
          pytest -v