name: Test Python

on: [push, pull_request]
#Para que lo podamos ejecutar manualmente desde github
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Python set up
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
    #Setiamos los secrets
      - name: Set environment variables for testing
        run: echo "Environment variables for tests are set."
        env:
          REDSHIFT_HOST: ${{ secrets.REDSHIFT_HOST }}
          REDSHIFT_PORT: ${{ secrets.REDSHIFT_PORT }}
          REDSHIFT_DB: ${{ secrets.REDSHIFT_DB }}
          REDSHIFT_USER: ${{ secrets.REDSHIFT_USER }}
          REDSHIFT_PASSWORD: ${{ secrets.REDSHIFT_PASSWORD }}

      - name: Dependencies
        run: pip install -r requirements.txt
        env:
          REDSHIFT_HOST: ${{ secrets.REDSHIFT_HOST }}
          REDSHIFT_PORT: ${{ secrets.REDSHIFT_PORT }}
          REDSHIFT_DB: ${{ secrets.REDSHIFT_DB }}
          REDSHIFT_USER: ${{ secrets.REDSHIFT_USER }}
          REDSHIFT_PASSWORD: ${{ secrets.REDSHIFT_PASSWORD }}
  #Corremos los test
      - name: Run test
        run: |
          pytest -v
        env:
          REDSHIFT_HOST: ${{ secrets.REDSHIFT_HOST }}
          REDSHIFT_PORT: ${{ secrets.REDSHIFT_PORT }}
          REDSHIFT_DB: ${{ secrets.REDSHIFT_DB }}
          REDSHIFT_USER: ${{ secrets.REDSHIFT_USER }}
          REDSHIFT_PASSWORD: ${{ secrets.REDSHIFT_PASSWORD }}