name: Test Python

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Python set up
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Set environment variables for testing
        run: echo "Environment variables for tests are set."
        env:
          REDSHIFT_HOST: ${{ secrets.REDSHIFT_HOST }}
          REDSHIFT_PORT: ${{ secrets.REDSHIFT_PORT }}
          REDSHIFT_DB: ${{ secrets.REDSHIFT_DB }}
          REDSHIFT_USER: ${{ secrets.REDSHIFT_USER }}
          REDSHIFT_PASSWORD: ${{ secrets.REDSHIFT_PASSWORD }}

      - name: Verify environment variables
        run: |
          echo "Host: $REDSHIFT_HOST"
          echo "Port: $REDSHIFT_PORT"
          echo "Database: $REDSHIFT_DB"
          echo "User: $REDSHIFT_USER"


      - name: Dependencies
        run: pip install -r requirements.txt

      - name: Run test
        run: |
          pytest -v
