name: Test Python

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install python
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install -r requirements.txt


      - name: Run test
        run: |
          source venv/bin/activate
          pytest ./test
